/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TaskViewImpl.java
 *
 * Created on 22-ene-2011, 11:59:09
 */
package view.task;

import controller.TaskController;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;
import model.TaskModel;
import model.entity.Task;
import view.AbstractViewImp;

/**
 *
 * @author javidgon
 */
public class TaskViewImpl extends AbstractViewImp<TaskController, TaskModel> implements TaskView {

    private TaskTableAndComboModel tableModelProximo;
    private TaskTableAndComboModel tableModelAlgunDia;
    private TaskTableAndComboModel tableModelProyecto;
    private TaskTableAndComboModel tableModelEnEspera;
    private TaskViewImplInternal paneltask;

    /** Creates new form TaskViewImpl */
    public TaskViewImpl() {
        tableModelProximo = new TaskTableAndComboModel("");
        tableModelAlgunDia = new TaskTableAndComboModel("");
        tableModelProyecto = new TaskTableAndComboModel("");
        tableModelEnEspera = new TaskTableAndComboModel("");
        this.paneltask = new TaskViewImplInternal(this);
        initComponents();
        this.jPanelCliente.add(this.paneltask);



    }

    public void init() {

        initComponents();
        tableModelProximo.setTasks(getModel().listar(getController().leerCategoria("1")));
        tableModelAlgunDia.setTasks(getModel().listar(getController().leerCategoria("2")));
        tableModelProyecto.setTasks(getModel().listar(getController().leerCategoria("3")));
        tableModelEnEspera.setTasks(getModel().listar(getController().leerCategoria("4")));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTableEnEspera = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProyecto = new javax.swing.JTable();
        jPanelCliente = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableAlgunDia1 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableProximo1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelCongratulations = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelCounter = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelMoney = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelEarnings = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelMinutes = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1070, 600));

        jTableEnEspera.setModel(tableModelEnEspera);
        jTableEnEspera.setSize(new java.awt.Dimension(450, 50));
        jTableEnEspera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEnEsperaTaskMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableEnEspera);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("   ");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("   ");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("   ");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("   ");

        jTableProyecto.setModel(tableModelProyecto);
        jTableProyecto.setSize(new java.awt.Dimension(450, 50));
        jTableProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProyectoTaskMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableProyecto);

        jPanelCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelCliente.setLayout(new javax.swing.BoxLayout(jPanelCliente, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Estadísticas:");

        jTableAlgunDia1.setModel(tableModelAlgunDia);
        jTableAlgunDia1.setSize(new java.awt.Dimension(450, 50));
        jTableAlgunDia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlgunDia1TaskMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableAlgunDia1);

        jTableProximo1.setModel(tableModelProximo);
        jTableProximo1.setSize(new java.awt.Dimension(450, 50));
        jTableProximo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProximo1TaskMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableProximo1);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Crear una nueva tarea:");

        jLabelCongratulations.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        jLabelCongratulations.setForeground(new java.awt.Color(255, 0, 0));
        jLabelCongratulations.setText("  ");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        jLabel10.setText("Time:");

        jLabelCounter.setForeground(new java.awt.Color(204, 0, 0));
        jLabelCounter.setText("0");

        jLabel11.setText("seconds");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel12.setForeground(new java.awt.Color(0, 153, 0));
        jLabel12.setText("You've lost ");

        jLabel13.setForeground(new java.awt.Color(0, 153, 0));
        jLabel13.setText("euros");

        jLabelMoney.setForeground(new java.awt.Color(153, 0, 0));
        jLabelMoney.setText("  ");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        jLabel14.setForeground(new java.awt.Color(0, 153, 0));
        jLabel14.setText("You've won ");

        jLabelEarnings.setForeground(new java.awt.Color(0, 51, 255));
        jLabelEarnings.setText("0");

        jLabel16.setForeground(new java.awt.Color(0, 153, 0));
        jLabel16.setText("euros!");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 0));
        jLabel15.setText("Price per hour:");

        jLabelMinutes.setText("  ");

        jLabel17.setForeground(new java.awt.Color(0, 153, 0));
        jLabel17.setText("euros");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelID)
                    .add(layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelCounter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel11)
                        .add(110, 110, 110)
                        .add(jLabelCongratulations, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 490, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 184, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(186, 186, 186)
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(272, 272, 272)
                        .add(jLabel6))
                    .add(layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 350, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(20, 20, 20)
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 360, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(32, 32, 32)
                        .add(jPanelCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 330, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(250, 250, 250)
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(240, 240, 240)
                        .add(jLabel5))
                    .add(layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 350, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(20, 20, 20)
                        .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 360, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(50, 50, 50)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel12)
                                .add(13, 13, 13)
                                .add(jLabelMoney, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel13))
                            .add(layout.createSequentialGroup()
                                .add(jLabel15)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabelMinutes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabel17))
                            .add(layout.createSequentialGroup()
                                .add(jLabel14)
                                .add(5, 5, 5)
                                .add(jLabelEarnings)
                                .add(20, 20, 20)
                                .add(jLabel16)))))
                .add(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabelID)
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(3, 3, 3)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel10)
                            .add(jLabelCounter)
                            .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabelCongratulations)))
                .add(14, 14, 14)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jLabel6)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanelCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(8, 8, 8)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(layout.createSequentialGroup()
                        .add(2, 2, 2)
                        .add(jLabel4))
                    .add(layout.createSequentialGroup()
                        .add(8, 8, 8)
                        .add(jLabel5)))
                .add(2, 2, 2)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 210, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 210, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel15)
                            .add(jLabelMinutes)
                            .add(jLabel17))
                        .add(13, 13, 13)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel14)
                            .add(jLabelEarnings)
                            .add(jLabel16))
                        .add(13, 13, 13)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel12)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabelMoney)
                                .add(jLabel13))))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableProyectoTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProyectoTaskMouseClicked

        TaskTableAndComboModel ctm = (TaskTableAndComboModel) this.jTableProyecto.getModel();
        Task task = ctm.getRow(this.jTableProyecto.getSelectedRow());
        paneltask.setTask(task);

    }//GEN-LAST:event_jTableProyectoTaskMouseClicked

    private void jTableEnEsperaTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEnEsperaTaskMouseClicked

        TaskTableAndComboModel ctm = (TaskTableAndComboModel) this.jTableEnEspera.getModel();
        Task task = ctm.getRow(this.jTableEnEspera.getSelectedRow());
        paneltask.setTask(task);

    }//GEN-LAST:event_jTableEnEsperaTaskMouseClicked

    private void jTableAlgunDia1TaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlgunDia1TaskMouseClicked

        TaskTableAndComboModel ctm = (TaskTableAndComboModel) this.jTableAlgunDia1.getModel();
        Task task = ctm.getRow(this.jTableAlgunDia1.getSelectedRow());
        paneltask.setTask(task);

    }//GEN-LAST:event_jTableAlgunDia1TaskMouseClicked

    private void jTableProximo1TaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProximo1TaskMouseClicked

        TaskTableAndComboModel ctm = (TaskTableAndComboModel) this.jTableProximo1.getModel();
        Task task = ctm.getRow(this.jTableProximo1.getSelectedRow());
        paneltask.setTask(task);

    }//GEN-LAST:event_jTableProximo1TaskMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCongratulations;
    private javax.swing.JLabel jLabelCounter;
    private javax.swing.JLabel jLabelEarnings;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelMinutes;
    private javax.swing.JLabel jLabelMoney;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableAlgunDia1;
    private javax.swing.JTable jTableEnEspera;
    private javax.swing.JTable jTableProximo1;
    private javax.swing.JTable jTableProyecto;
    // End of variables declaration//GEN-END:variables

    public JLabel getLabelCongratulations() {

        return jLabelCongratulations;
    }

    public TaskTableAndComboModel getTableModelProyecto() {
        return tableModelProyecto;
    }

    public JLabel getLabelCounter() {

        return jLabelCounter;
    }

    public void refresh() {
        jTableProximo1.clearSelection();
        jTableAlgunDia1.clearSelection();
        jTableEnEspera.clearSelection();
        jTableProyecto.clearSelection();
        tableModelProximo.setTasks(getModel().listar(getController().leerCategoria("1")));
        tableModelAlgunDia.setTasks(getModel().listar(getController().leerCategoria("2")));
        tableModelProyecto.setTasks(getModel().listar(getController().leerCategoria("3")));
        tableModelEnEspera.setTasks(getModel().listar(getController().leerCategoria("4")));
        this.paneltask.refresh();
        loadCategories();
    }

    protected void fireNuevoTaskGesture(String description, String type, String value) {
        List<String> datos = new ArrayList<String>();
        datos.add(description);
        datos.add(type);
        datos.add(value);
        getController().nuevaEntidadGesture(datos);



    }

    public void contador(final int valor) {

        final Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {

            int i = valor;

            public void run() {
                jLabelCounter.setText(String.valueOf(i++));
            }
        }, 0, 1000);
    }

    public void ticks(final float money) {

        final Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {

            int i = 0;

            public void run() {
                jLabelMoney.setText(String.valueOf((i++) * money));
                /*if (i > valor)
                timer.cancel();*/
            }
        }, 0, 1000);
    }

    protected void fireActualizaTaskGesture(String description, String type, String value) {
        List<String> datos = new ArrayList<String>();
        datos.add(description);
        datos.add(type);
        datos.add(value);
        getController().actualizaEntidadGesture(datos);

    }

    public void fireBorraTaskGesture(String description) {
        getController().borraEntidadGesture(description);

    }

    protected void fireRealizarTaskGesture(String description) {

        getController().realizarEntidadGesture(description);

    }

    public JLabel getjLabelEarnings() {
        return jLabelEarnings;
    }

    public void setjLabelEarnings(JLabel jLabelEarnings) {
        this.jLabelEarnings = jLabelEarnings;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public TaskViewImplInternal getPaneltask() {
        return paneltask;
    }

    public JLabel getjLabelMinutes() {
        return jLabelMinutes;
    }

    public void setjLabelMinutes(JLabel jLabelMinutes) {
        this.jLabelMinutes = jLabelMinutes;
    }

    public void loadCategories() {

        this.jLabel1.setText(getController().leerCategoria("1"));
        this.jLabel2.setText(getController().leerCategoria("2"));
        this.jLabel3.setText(getController().leerCategoria("3"));
        this.jLabel4.setText(getController().leerCategoria("4"));

    }
}
