/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OptionsViewImpl.java
 *
 * Created on 28-ene-2011, 13:54:21
 */

package view.options;


import view.task.TaskView;

/**
 *
 * @author javidgon
 */
public class OptionsViewImpl extends javax.swing.JPanel {
    private TaskView taskView;
    /** Creates new form OptionsViewImpl */
    public OptionsViewImpl(TaskView taskView) {
        initComponents();
        this.taskView = taskView;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextCategory1 = new javax.swing.JTextField();
        jTextCategory2 = new javax.swing.JTextField();
        jTextCategory3 = new javax.swing.JTextField();
        jTextCategory4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelError1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Options");

        jLabel2.setText("Change name of categories:");

        jLabel4.setText("Category 1: ");

        jLabel5.setText("Category 2:");

        jLabel6.setText("Category 3:");

        jLabel7.setText("Category 4:");

        jButton1.setText("Apply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextCategory4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCategory4ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("¡Atención! Si cambia el nombre perderá los datos que tenía guardados.");

        jLabel9.setText("Errores:");

        jLabelError1.setForeground(new java.awt.Color(204, 0, 0));
        jLabelError1.setText("   ");

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel4)
                                    .add(jLabel5)
                                    .add(jLabel6)
                                    .add(jLabel7))
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTextCategory4)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTextCategory3)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTextCategory2)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTextCategory1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 101, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelError1)
                            .add(jLabel9))))
                .addContainerGap(278, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel8)
                .addContainerGap(281, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton2)
                .addContainerGap(568, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(33, 33, 33)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabel9))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(jTextCategory1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel5)
                            .add(jTextCategory2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel6)
                            .add(jTextCategory3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel7)
                            .add(jTextCategory4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jLabelError1))
                .add(18, 18, 18)
                .add(jLabel8)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(!this.jTextCategory1.getText().equals("") && !this.jTextCategory2.getText().equals("") && !this.jTextCategory3.getText().equals("") && !this.jTextCategory4.getText().equals("")){
            taskView.getController().actualizarCategoria("1", this.jTextCategory1.getText());
            taskView.getController().actualizarCategoria("2", this.jTextCategory2.getText());
            taskView.getController().actualizarCategoria("3", this.jTextCategory3.getText());
            taskView.getController().actualizarCategoria("4", this.jTextCategory4.getText());
            taskView.refresh();

            // Proximos añadidos. Eliminación de tareas residuales, cambios de nombre y botón START!

        }else{
            this.jLabelError1.setText("Tiene que rellenar todas casillas.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextCategory4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCategory4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCategory4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cargarCategorias();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelError1;
    private javax.swing.JTextField jTextCategory1;
    private javax.swing.JTextField jTextCategory2;
    private javax.swing.JTextField jTextCategory3;
    private javax.swing.JTextField jTextCategory4;
    // End of variables declaration//GEN-END:variables

    public void cargarCategorias(){
        this.jTextCategory1.setText(taskView.getModel().leerCategoria("1"));
        this.jTextCategory2.setText(taskView.getModel().leerCategoria("2"));
        this.jTextCategory3.setText(taskView.getModel().leerCategoria("3"));
        this.jTextCategory4.setText(taskView.getModel().leerCategoria("4"));
    }
}
