/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GlobalView.java
 *
 * Created on 22-ene-2011, 13:39:21
 */

package view;

import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import view.options.OptionsViewImpl;
import view.task.TaskView;
import view.tasksAccomplished.TasksAccomplishedViewImpl;
import view.welcome.WelcomeViewImpl;

/**
 *
 * @author javidgon
 */
public class GlobalView extends javax.swing.JFrame {
    private TaskView taskView;
    private WelcomeViewImpl welcomeView;
    private TasksAccomplishedViewImpl tasksAccomplished;
    private OptionsViewImpl optionsView;

    /** Creates new form VistaGlobal */
    public GlobalView(TaskView taskView,WelcomeViewImpl welcomeView, TasksAccomplishedViewImpl tasksAccomplished, OptionsViewImpl optionsView) {
        this.taskView=taskView;
        this.welcomeView = welcomeView;
        this.tasksAccomplished = tasksAccomplished;
        this.optionsView = optionsView;
        initComponents();
        this.jTabbedPane1.add("Welcome",this.welcomeView);
        this.jTabbedPane1.add("Taks",(JPanel)taskView);
        this.jTabbedPane1.add("Tasks Accomplished",this.tasksAccomplished);
        this.jTabbedPane1.add("Options",this.optionsView);
        this.setTitle("iProductivity App");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("iProductivity");
        setMinimumSize(new java.awt.Dimension(1200, 600));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlobalView().setVisible(true);
            }
        });
    }
*/
    public void display() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
                taskView.display();
                tasksAccomplished.display();
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

 


}