/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WelcomeViewImpl.java
 *
 * Created on 23-ene-2011, 17:52:03
 */

package view.welcome;

import view.task.TaskView;

/**
 *
 * @author javidgon
 */
public class WelcomeViewImpl extends javax.swing.JPanel {
    private TaskView view;
    /** Creates new form WelcomeViewImpl */
    public WelcomeViewImpl(TaskView view) {
        initComponents();
        this.view=view;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTime = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEuros = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setEnabled(false);
        setMinimumSize(new java.awt.Dimension(21, 21));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 24));
        jLabel1.setText("Welcome to iProductivity App");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        jLabel2.setText("Set how much time you will be with task:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        jTextFieldTime.setText("120");
        add(jTextFieldTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 70, -1));

        jButton1.setText("Go ahead!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        jLabel3.setText("minutes");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, -1, -1));

        jLabel4.setText("Set how much money you use to earn every hour:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        jTextFieldEuros.setText("7");
        add(jTextFieldEuros, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 70, -1));

        jLabel5.setText("euros");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int minutes = Integer.parseInt(this.jTextFieldTime.getText());
        view.contador(minutes*60);
        float price = Integer.parseInt(this.jTextFieldEuros.getText());
        view.ticks(price/3600);
        view.getjLabelMinutes().setText(String.valueOf((int)price));
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldEuros;
    private javax.swing.JTextField jTextFieldTime;
    // End of variables declaration//GEN-END:variables

}
