/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TasksAccomplishedViewImpl.java
 *
 * Created on 27-ene-2011, 13:52:27
 */

package view.tasksAccomplished;

import javax.swing.JTable;
import model.TaskModelImpl;
import model.entity.Task;
import model.entity.TaskImpl;
import view.task.TaskTableAndComboModel;
import view.task.TaskTableAndComboModelAccomplished;
import view.task.TaskView;

/**
 *
 * @author javidgon
 */
public class TasksAccomplishedViewImpl extends javax.swing.JPanel {
    private TaskView taskView;
    private TaskModelImpl taskModel;
    private TaskTableAndComboModelAccomplished tableModelAccomplished;
    /** Creates new form TasksAccomplishedViewImpl */
    public TasksAccomplishedViewImpl(TaskView taskView) {
        tableModelAccomplished = new TaskTableAndComboModelAccomplished("1");
        initComponents();
        this.taskModel = new TaskModelImpl();
        this.taskView = taskView;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableProximo1 = new javax.swing.JTable();
        jButtonRefresh = new javax.swing.JButton();
        jLabelText = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Tareas completadas");

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Estás seguro de que la quieres borrar definitivamente?");

        jTableProximo1.setModel(this.tableModelAccomplished);
        jTableProximo1.setSize(new java.awt.Dimension(450, 50));
        jTableProximo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProximo1TaskMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableProximo1);

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jLabelText.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelText.setText("  ");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 414, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(112, 112, 112)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButtonRefresh)
                            .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabelText)
                            .add(jLabel2)))
                    .add(jLabel1))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(44, 44, 44)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabelText)
                        .add(18, 18, 18)
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonRefresh))
                    .add(layout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 350, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.taskView.fireBorraTaskGesture(this.jLabelText.getText());
        this.refresh();
        this.jLabelText.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

      private void jTableProximo1TaskMouseClicked(java.awt.event.MouseEvent evt) {

        TaskTableAndComboModelAccomplished ctm = (TaskTableAndComboModelAccomplished) this.jTableProximo1.getModel();
        Task task = ctm.getRow(this.jTableProximo1.getSelectedRow());
        jLabelText.setText(task.getDescription());

    }
      /**/
    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        tableModelAccomplished = new TaskTableAndComboModelAccomplished("1");
        this.jTableProximo1.setModel(tableModelAccomplished);
    }

    public TaskTableAndComboModelAccomplished getTableModelAccomplished() {
        return tableModelAccomplished;
    }

    public JTable getjTableProximo1() {
        return jTableProximo1;
    }//GEN-LAST:event_jButtonRefreshActionPerformed
/*
    private void jTableProximo1TaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProximo1TaskMouseClicked


    }//GEN-LAST:event_jTableProximo1TaskMouseClicked
*/
    public void setTableModelAccomplished(TaskTableAndComboModelAccomplished tableModelAccomplished) {
        this.tableModelAccomplished = tableModelAccomplished;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelText;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableProximo1;
    // End of variables declaration//GEN-END:variables

public TaskTableAndComboModelAccomplished getModel(){

    return this.tableModelAccomplished;

}

public void display(){
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                setVisible(true);
                refresh();
            }
        });

    }
    public void refresh() {

    tableModelAccomplished.setTasks(taskModel.listDone("1"));
    }
}
